# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eceabad4bac23982a266e54f229d8962936b071e3d0cb709d2a02a8239416b810d7ffb125cc5245f6fef1973614aa967844e13bef9d2882c82d4a94228f6732

test:
  secret_key_base: 6d36f93bffb01d5e0b43983fca2518f19ff1fc487ed25dfc4a2da1962b3ca74ae3fb9222d3d40f73fa50188a0c122f2dbfba3e7bf030e6c516c7771f4157871d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
